In [2]:
import dart_fss as dart
import os
import pandas as pd
import numpy as np
import openpyxl

In [3]:
df_local_samsung=pd.read_excel('C:/Users/TJ/PycharmProjects/PY/dart/dart_cashflow/samsung_pandas.xlsx')

In [4]:
df_local_samsung

,Unnamed: 0,"[D520000] Statement of cash flows, indirect method - Consolidated financial statements (Unit: KRW)",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,20200101-20201231,Unnamed: 9,20190101-20191231,Unnamed: 11,20180101-20181231,Unnamed: 13
0,NaN,concept_id,label_ko,label_en,class0,class1,class2,class3,"('연결재무제표',)","('별도재무제표',)","('연결재무제표',)","('별도재무제표',)","('별도재무제표',)","('연결재무제표',)"
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,ifrs-full_CashFlowsFromUsedInOperatingActivities,영업활동 현금흐름,Cash flows from (used in) operating activities,현금흐름표 [abstract],영업활동 현금흐름,NaN,NaN,65287009000000,37509025000000,45382915000000,22796257000000,44341217000000,67031863000000
3,1.0,entity00126380_udf_CF_201710211099539_CashFlow...,영업에서 창출된 현금흐름,Cash generated from operations,현금흐름표 [abstract],영업활동 현금흐름,영업에서 창출된 현금흐름,NaN,68148810000000,NaN,56635791000000,NaN,NaN,78025064000000
4,2.0,entity00126380_udf_CF_201710211092510_udf_CF_2...,당기순이익,Profit (loss) for the year,현금흐름표 [abstract],영업활동 현금흐름,영업에서 창출된 현금흐름,당기순이익,26407832000000,NaN,21738865000000,NaN,NaN,44344857000000
5,3.0,entity00126380_udf_CF_2017102110929616_udf_CF_...,조정,Adjustments,현금흐름표 [abstract],영업활동 현금흐름,영업에서 창출된 현금흐름,조정,41618554000000,NaN,37442682000000,NaN,NaN,43604573000000
6,4.0,entity00126380_udf_CF_2017102110934928_udf_CF_...,영업활동으로 인한 자산부채의 변동,Changes in assets and liabilities arising from...,현금흐름표 [abstract],영업활동 현금흐름,영업에서 창출된 현금흐름,영업활동으로 인한 자산부채의 변동,122424000000,NaN,-2545756000000,NaN,NaN,-9924366000000
7,5.0,ifrs-full_InterestReceivedClassifiedAsOperatin...,이자의 수취,Interest received,현금흐름표 [abstract],영업활동 현금흐름,이자의 수취,NaN,2220209000000,448323000000,2306401000000,673363000000,459074000000,1788520000000
8,6.0,ifrs-full_InterestPaidClassifiedAsOperatingAct...,이자의 지급,Interest paid,현금흐름표 [abstract],영업활동 현금흐름,이자의 지급,NaN,555321000000,148262000000,579979000000,306633000000,343270000000,548272000000
9,7.0,ifrs-full_DividendsReceivedClassifiedAsOperati...,배당금 수입,Dividends received,현금흐름표 [abstract],영업활동 현금흐름,배당금 수입,NaN,243666000000,129569000000,241801000000,4625181000000,779567000000,215992000000
10,8.0,ifrs-full_IncomeTaxesPaidRefundClassifiedAsOpe...,법인세 납부액,Income taxes paid,현금흐름표 [abstract],영업활동 현금흐름,법인세 납부액,NaN,4770355000000,2462259000000,13221099000000,10540360000000,10150465000000,12449441000000
11,9.0,ifrs-full_CashFlowsFromUsedInInvestingActivities,투자활동 현금흐름,Cash flows from investing activities,현금흐름표 [abstract],투자활동 현금흐름,NaN,NaN,-53628591000000,-31175575000000,-39948171000000,-13537171000000,-31678548000000,-52240453000000
12,10.0,entity00126380_udf_CF_2017102110167395_CashFlo...,단기금융상품의 순감소(증가),Net decrease (increase) in short-term financia...,현금흐름표 [abstract],투자활동 현금흐름,단기금융상품의 순감소(증가),NaN,-20369616000000,NaN,-2030913000000,NaN,NaN,-12368298000000
13,11.0,entity00126380_udf_CF_201987152650384_CashFlow...,단기상각후원가금융자산의 순감소(증가),Net decrease (increase) in short-term financia...,현금흐름표 [abstract],투자활동 현금흐름,단기상각후원가금융자산의 순감소(증가),NaN,184104000000,NaN,-818089000000,NaN,NaN,-1436844000000
14,12.0,entity00126380_udf_CF_2019726153251267_CashFlo...,단기당기손익-공정가치금융자산의 순감소(증가),Net decrease (increase) in short-term financia...,현금흐름표 [abstract],투자활동 현금흐름,단기당기손익-공정가치금융자산의 순감소(증가),NaN,1704512000000,NaN,374982000000,NaN,NaN,-139668000000
15,13.0,dart_ProceedsFromSalesOfLongTermFinancialInstr...,장기금융상품의 처분,Disposal of long-term financial instruments,현금흐름표 [abstract],투자활동 현금흐름,장기금융상품의 처분,NaN,12184301000000,0,4586610000000,1400000000000,0,255850000000
16,14.0,dart_PurchaseOfLongTermFinancialInstruments,장기금융상품의 취득,Acquisition of long-term financial instruments,현금흐름표 [abstract],투자활동 현금흐름,장기금융상품의 취득,NaN,8019263000000,0,12725465000000,0,1860000000000,7678654000000
17,15.0,entity00126380_udf_CF_2020721111020612_CashFlo...,상각후원가금융자산의 처분,Disposal of financial assets at amortized cost,현금흐름표 [abstract],투자활동 현금흐름,상각후원가금융자산의 처분,NaN,1023117000000,NaN,694584000000,NaN,NaN,0
18,16.0,entity00126380_udf_CF_2018510204028298_CashFlo...,상각후원가금융자산의 취득,Acquisition of financial assets at amortized cost,현금흐름표 [abstract],투자활동 현금흐름,상각후원가금융자산의 취득,NaN,0,NaN,-825027000000,NaN,NaN,-158716000000
19,17.0,entity00126380_udf_CF_2018510204038291_CashFlo...,기타포괄손익-공정가치금융자산의 처분,Disposal of financial assets at fair value thr...,현금흐름표 [abstract],투자활동 현금흐름,기타포괄손익-공정가치금융자산의 처분,NaN,32128000000,NaN,1575000000,NaN,NaN,16211000000
20,18.0,entity00126380_udf_CF_2018510204040276_CashFlo...,기타포괄손익-공정가치금융자산의 취득,Acquisition of financial assets at fair value ...,현금흐름표 [abstract],투자활동 현금흐름,기타포괄손익-공정가치금융자산의 취득,NaN,-245497000000,NaN,-63773000000,NaN,NaN,-456134000000
21,19.0,entity00126380_udf_CF_2018510204036276_CashFlo...,당기손익-공정가치금융자산의 처분,Disposal of financial assets at fair value thr...,현금흐름표 [abstract],투자활동 현금흐름,당기손익-공정가치금융자산의 처분,NaN,39746000000,NaN,64321000000,NaN,NaN,80138000000
22,20.0,entity00126380_udf_CF_2018510204025664_CashFlo...,당기손익-공정가치금융자산의 취득,Acquisition of financial assets at fair value ...,현금흐름표 [abstract],투자활동 현금흐름,당기손익-공정가치금융자산의 취득,NaN,-84184000000,NaN,-135826000000,NaN,NaN,-193848000000
23,21.0,entity00126380_udf_CF_2020721111339866_CashFlo...,관계기업 및 공동기업 투자의 처분,Disposal of investment in associates and joint...,현금흐름표 [abstract],투자활동 현금흐름,관계기업 및 공동기업 투자의 처분,NaN,0,NaN,12149000000,NaN,NaN,148000000
24,22.0,entity00126380_udf_CF_20171021101629633_CashFl...,관계기업 및 공동기업 투자의 취득,Acquisition of investment in associates and jo...,현금흐름표 [abstract],투자활동 현금흐름,관계기업 및 공동기업 투자의 취득,NaN,-83280000000,NaN,-12778000000,NaN,NaN,-51226000000
25,23.0,ifrs-full_ProceedsFromSalesOfPropertyPlantAndE...,유형자산의 처분,"Disposal of property, plant and equipment",현금흐름표 [abstract],투자활동 현금흐름,유형자산의 처분,NaN,376744000000,431142000000,513265000000,600901000000,340558000000,556973000000
26,24.0,ifrs-full_PurchaseOfPropertyPlantAndEquipmentC...,유형자산의 취득,"Acquisition of property, plant and equipment",현금흐름표 [abstract],투자활동 현금흐름,유형자산의 취득,NaN,37592034000000,26962042000000,25367756000000,17240242000000,21387378000000,29556406000000
27,25.0,ifrs-full_ProceedsFromSalesOfIntangibleAssetsC...,무형자산의 처분,Disposal of intangible assets,현금흐름표 [abstract],투자활동 현금흐름,무형자산의 처분,NaN,7027000000,1082000000,7241000000,1965000000,706000000,11935000000
28,26.0,ifrs-full_PurchaseOfIntangibleAssetsClassified...,무형자산의 취득,Acquisition of intangible assets,현금흐름표 [abstract],투자활동 현금흐름,무형자산의 취득,NaN,2679779000000,2239834000000,3249914000000,2855959000000,880032000000,1020517000000
29,27.0,entity00126380_udf_CF_20171021101626447_CashFl...,사업결합으로 인한 현금유출액,Cash outflow from business combinations,현금흐름표 [abstract],투자활동 현금흐름,사업결합으로 인한 현금유출액,NaN,-49420000000,NaN,-1019405000000,NaN,NaN,-99108000000
30,28.0,entity00126380_udf_CF_20171021101625672_CashFl...,기타투자활동으로 인한 현금유출입액,Cash inflow (outflow) from other investing act...,현금흐름표 [abstract],투자활동 현금흐름,기타투자활동으로 인한 현금유출입액,NaN,-57197000000,NaN,46048000000,NaN,NaN,-2289000000
31,29.0,ifrs-full_CashFlowsFromUsedInFinancingActivities,재무활동 현금흐름,Cash flows from financing activities,현금흐름표 [abstract],재무활동 현금흐름,NaN,NaN,-8327839000000,-7426376000000,-9484510000000,-9787719000000,-12818480000000,-15090222000000
32,30.0,entity00126380_udf_CF_20171021102249949_CashFl...,단기차입금의 순증가(감소),Net increase (decrease) in short-term borrowings,현금흐름표 [abstract],재무활동 현금흐름,단기차입금의 순증가(감소),NaN,2191186000000,NaN,865792000000,NaN,NaN,-2046470000000
33,31.0,dart_AcquisitionOfTreasuryShares,자기주식의 취득,Acquisition of treasury shares,현금흐름표 [abstract],재무활동 현금흐름,자기주식의 취득,NaN,0,0,0,0,875111000000,875111000000
34,32.0,entity00126380_udf_CF_202128181427351_CashFlow...,장기차입금의 차입,Proceed from long-term borrowings,현금흐름표 [abstract],재무활동 현금흐름,장기차입금의 차입,NaN,14495000000,NaN,0,NaN,NaN,3580000000
35,33.0,dart_RepaymentsOfLongTermBorrowings,사채 및 장기차입금의 상환,Repayment of debentures and long-term borrowings,현금흐름표 [abstract],재무활동 현금흐름,사채 및 장기차입금의 상환,NaN,864947000000,134443000000,709400000000,128431000000,5357000000,1986597000000
36,34.0,ifrs-full_DividendsPaidClassifiedAsFinancingAc...,배당금의 지급,Dividends paid,현금흐름표 [abstract],재무활동 현금흐름,배당금의 지급,NaN,9676760000000,9618283000000,9639202000000,9618210000000,10141826000000,10193695000000
37,35.0,entity00126380_udf_CF_20171021102253395_CashFl...,비지배지분의 증감,Net increase (decrease) in non-controlling int...,현금흐름표 [abstract],재무활동 현금흐름,비지배지분의 증감,NaN,8187000000,NaN,-1700000000,NaN,NaN,8071000000
38,36.0,entity00126380_udf_CF_20201022202135156_Statem...,매각예정분류,Classified as held-for-sale,현금흐름표 [abstract],매각예정분류,NaN,NaN,-139000000,NaN,0,NaN,NaN,0
39,37.0,ifrs-full_EffectOfExchangeRateChangesOnCashAnd...,외화환산으로 인한 현금의 변동,Effect of exchange rate changes on cash and ca...,현금흐름표 [abstract],외화환산으로 인한 현금의 변동,NaN,NaN,-833861000000,54000000,595260000000,2593000000,0,94187000000
40,38.0,ifrs-full_IncreaseDecreaseInCashAndCashEquival...,현금및현금성자산의 순증감,Net increase (decrease) in cash and cash equiv...,현금흐름표 [abstract],현금및현금성자산의 순증감,NaN,NaN,2496579000000,-1092872000000,-3454506000000,-526040000000,-155811000000,-204625000000
41,39.0,dart_CashAndCashEquivalentsAtBeginningOfPeriodCf,기초의 현금및현금성자산,Cash and cash equivalents at beginning of period,현금흐름표 [abstract],기초의 현금및현금성자산,NaN,NaN,26885999000000,2081917000000,30340505000000,2607957000000,2763768000000,30545130000000
42,40.0,dart_CashAndCashEquivalentsAtEndOfPeriodCf,기말의 현금및현금성자산,Cash and cash equivalents at end of period,현금흐름표 [abstract],기말의 현금및현금성자산,NaN,NaN,29382578000000,989045000000,26885999000000,2081917000000,2607957000000,30340505000000

In [5]:
df_local_samsung['Unnamed: 0']

0      NaN
1      NaN
2      0.0
3      1.0
4      2.0
5      3.0
6      4.0
7      5.0
8      6.0
9      7.0
10     8.0
11     9.0
12    10.0
13    11.0
14    12.0
15    13.0
16    14.0
17    15.0
18    16.0
19    17.0
20    18.0
21    19.0
22    20.0
23    21.0
24    22.0
25    23.0
26    24.0
27    25.0
28    26.0
29    27.0
30    28.0
31    29.0
32    30.0
33    31.0
34    32.0
35    33.0
36    34.0
37    35.0
38    36.0
39    37.0
40    38.0
41    39.0
42    40.0
Name: Unnamed: 0, dtype: float64

In [6]:
df_local_samsung.columns

Index(['Unnamed: 0',
       '[D520000] Statement of cash flows, indirect method - Consolidated financial statements (Unit: KRW)',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', '20200101-20201231', 'Unnamed: 9', '20190101-20191231',
       'Unnamed: 11', '20180101-20181231', 'Unnamed: 13'],
      dtype='object')

In [7]:
# 데이터 사이언스 스쿨 연습문제 4.1.2
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990]}
columns=['주요지표','2015', '2010','2005', '2000']
index=['매출액','영업이익','경상이익','법인세차감전이익']
df=pd.DataFrame(data, index=index, columns=columns)
df

         주요지표     2015     2010     2005     2000
매출액       NaN  9904312  9631482  9762546  9853972
영업이익      NaN  3448737  3393191  3512547  3655437
경상이익      NaN  2890451  2632035  2517680  2466338
법인세차감전이익  NaN  2466052  2431774  2456016  2473990

In [11]:
# def df["주요지표"] # 이거 왜 안돼
df.drop(['주요지표'], axis=1)

             2015     2010     2005     2000
매출액       9904312  9631482  9762546  9853972
영업이익      3448737  3393191  3512547  3655437
경상이익      2890451  2632035  2517680  2466338
법인세차감전이익  2466052  2431774  2456016  2473990

In [18]:
df[1:2]
type(df[1:2])

pandas.core.frame.DataFrame

In [20]:
df.T["영업이익"]
type(df.T["영업이익"])

pandas.core.series.Series